In [2]:
import numpy as np

In [13]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
rando = np.random.randint(1,100,100)

In [40]:
rando

array([39, 76, 96, 27, 96, 18, 48, 84,  4, 25, 22, 89, 76, 19, 82, 69, 74,
       58, 86, 36, 11, 52, 76, 86, 22, 64, 61, 33, 64, 25, 64, 73, 84, 10,
       84, 57, 91,  3, 58, 86,  9, 63, 72, 52, 75, 89, 89, 35, 78, 69, 91,
       55, 85, 58, 67, 78, 30, 28, 96,  8, 39, 65,  8, 12, 91, 80, 40, 95,
       91, 35,  3, 95, 72,  6, 22, 83, 31, 58, 44, 70, 85,  8, 10, 98, 65,
       53,  2, 36, 51, 99, 20, 68, 88,  3, 45, 62, 69, 61, 54, 36])

In [41]:
rando.argmax()

89

In [42]:
rando[89]

99

In [44]:
rando = rando.reshape(10,10)

In [45]:
rando.shape

(10, 10)

In [46]:
rando.argmax()

89

In [47]:
rando.dtype

dtype('int64')

In [67]:
np.random.randint(5,10)

7